name: build-package
run-name: build-package

on:
  workflow_dispatch:  

jobs:
  build-package:
    name: build-package
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Install Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Install NuGet
        uses: nuget/setup-nuget@v2
        
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: dotnet build src/ZippyNeuron.Metarwiz.sln --configuration Release

      - name: Add NuGet Source
        run: dotnet nuget add source --username ZippyNeuron --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name GitHub "https://nuget.pkg.github.com/ZippyNeuron/index.json"

      - name: Publish Nuget Package
        run: dotnet nuget push "src/ZippyNeuron.Metarwiz/bin/Release/*.nupkg" --api-key ${{ secrets.PUSH_PACKAGE_TOKEN }} --source "GitHub"
  