name: continuous-integration
run-name: continuous-integration

on:
  push:
    branches:
    - master

jobs:
  continuous-integration:
    name: continuous-integration
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Install Dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
          
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build
      run: dotnet build src/ZippyNeuron.Metarwiz.sln --configuration Release