name: publish-nuget-org
run-name: publish-nuget-org

on:
  workflow_dispatch:  

jobs:
  build_package:
    name: publish-nuget-org
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Install Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build src/ZippyNeuron.Metarwiz.sln --configuration Release

      - name: Publish Nuget Package
        run: dotnet nuget push "src/ZippyNeuron.Metarwiz/bin/Release/*.nupkg" --api-key ${{ secrets.NUGET_ORG_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
