name: Publish Nuget
run-name: Publish Nuget

on:
  workflow_dispatch:  

jobs:
  build_package:
    name: Publish Nuget
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Install Dotnet
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.x
          
      - name: Install NuGet
        uses: NuGet/setup-nuget@v1.1.1
        
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Build
        run: dotnet build . --configuration Release

      - name: Publish Nuget Package
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Metarwiz/Metarwiz.csproj
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: ZippyNeuron.Metarwiz
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props
          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0
          # Flag to toggle git tagging, enabled by default
          # TAG_COMMIT: true
          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_ORG_KEY}}
          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://api.nuget.org
          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: false
