name: Publish Nuget
run-name: Publish Nuget

on:
  workflow_dispatch:  

jobs:
  build_package:
    name: Publish Nuget
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Install Dotnet
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.x
          
      - name: Install NuGet
        uses: NuGet/setup-nuget@v1.1.1
        
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Build
        run: dotnet build . --configuration Release

      - name: Publish Nuget Package
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: Metarwiz/Metarwiz.csproj
          PACKAGE_NAME: ZippyNeuron.Metarwiz
          NUGET_KEY: ${{secrets.NUGET_ORG_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: false
